### ISSUE TITLE
Bezeichnung

### ISSUE THREAD

**Issue by HoffmannP** [VeronaWorkgroup/VeronaInterface#1]
Zur Zeit existieren zwei verschiedene Bezeichnungen:

    20.09.2018 - "Item-Player interface definition v1.0" (mit z.b. dem Versionsattribut als string und damit dem Semantic Versioning zugänglich)
    11.03.2019 - "VERA online player interface definition v1.0" (Versionsattribut als number und damit nur hochzählbar.

Das Interface regelt die Kommunikation zwischen dem Testsystem und dem Player. Es erscheint mir eher ungünstig nur eine Seite der Kommunikation zu nennen. Das Wort "Item-Player" erscheint mir aufgrund der unklaren Definition des Begriffs "Item" ungünstig. Zudem hatten wir uns geeinigt "VERA online" zu "Verona" zusammenzufassen.
Aufgrund dieser Überlegungen schlage ich vor den vorliegenden Standard die "Verona Interface Definition" zu nennen.

**Comment by mechtelm** [comment]
Ich glaube, dass die Definition mehr braucht als die Player-Schnittstelle. Perspektivisch würde ich auch die Schnittstelle zum Autoren-Modul und zu Code-Modulen zur Verarbeitung der Antworten sehen. Daher wäre ich begrifflich für "Verona Player Interface Definition".
"Item" ist tatsächlich ein ungünstiger Begriff. Ich verwende Unit, was aber auch nicht klarer ist. Es reicht - hoffe ich - einfach "Player".
Der Player ist zwar nur eine Seite der Komunikation, aber die entscheidende. Denn ob die andere Seite ein Testcenter oder eine Demo-Seite oder Preview im Autorensystem ist, das ist offen.

**Comment by mechtelm** [comment]
Die andere Seite der Kommunikation kann man ja universell als "Player-Host" bezeichnen.

**Comment by HoffmannP** [comment]
Ich finde "Verona Player Interface Definition" auch gut. Für mich ist Unit die Bezeichnung einer Aufgabe (mit eventuell Subunit) und im Normalfall einem Stimulus. Ein Item ist für mich eine "Feld" in einer Datentabelle mit einer eindeutigen Bezeichnung und Zeile in der Itemtabelle. Vielleicht könnte man das mal irgendwohin schreiben
