### ISSUE TITLE
Weitere Nachrichten, weitere Knoten in der Nachricht

### ISSUE THREAD

**Issue by HoffmannP** [VeronaWorkgroup/VeronaInterface#10]
Wir hatten das Thema kurz angeschnitten, ich hätte jedoch gerne eine abschließende Meinung zu der Frage ob weitere unspezifizierte Nachrichten und Knoten in Nachrichten zulässig sein sollten.

**Comment by mechtelm** [comment]
Wir haben stets davon gesprochen, dass die Schnittstelle weiterentwickelt wird, um spezifischen Anforderungen der Beteiligten gerecht zu werden. Dazu ist sicherlich Dialog nötig, um beieinander zu bleiben, und ich hoffe, dass wir uns ausreichend Zeit dafür nehmen können.

Wenn jetzt die Schnittstelle ohne diesen Dialog aufgebohrt wird, dann sehe ich da erstmal kein Problem, weil Player bzw. Hosts, die das nicht verstehen, halt nicht wie erwartet reagieren, aber auch nicht abstürzen. Gerade in der Annäherungsphase unserer Systeme kann das klug sein, um Varianten der Datenübermittlung auszuprobieren.

**Comment by HoffmannP** [comment]
Umgesetzt
