### ISSUE TITLE
Versionsnummer

### ISSUE THREAD

**Issue by HoffmannP** [VeronaWorkgroup/VeronaInterface#2]
Bei der Versionsnummer halte ich auf der einen Seite ein Hochzählen (z.B. auf v1.1.0) für notwendig, um klar zu machen, dass die Neubenennung und Umstellung auf aktuelle Form die aktuellste Version bezeichnet.
Auf der anderen Seite ist die Definition bisher nur von einem Partner umgesetzt und somit noch hoch variable und evtl. noch im Status einer initialen Entwicklung. Das würde für eine Pre-Version in der Form 0.x.y sprechen.
Glücklicherweise sind bisher nur zwei Stellen der Versionsnummer veröffentlicht. Wir können also ganz frech die erste Stelle noch als "0." hinzufügen und dann die Verona Interface Definition (VID) unter v0.1.1 oder v0.2.0 veröffentlichen.

**Comment by mechtelm** [comment]
Finde ich gut.
