### ISSUE TITLE
Änderung des Typs der ReadyNotification.version

### ISSUE THREAD

**Issue by HoffmannP** [VeronaWorkgroup/VeronaInterface#3]
Da sich die meisten Softwareprojekte inzwischen auf eine [semantic versioning](https://semver.org/)  verständigt haben würde ich diesem Rationalisierungsprozess gerne folgen und die VID dementsprechend veröffentlichen. Da zwischen MINOR-Versionen Funktionalitätsunterschiede exisiteren können ist bei der Angabe der kompatiblen Version daher mindestens diese Information mit anzugeben.
Eine vollständige Kompatibilitätsspezifikation ließe sich [equivalent zu npm](https://semver.npmjs.com/) angeben.

Ich plädiere daher für die Umwandlung in einen string Typ der dem oben angegebenen Format gehorcht.

**Comment by mechtelm** [comment]
Finde ich gut.
