### ISSUE TITLE
srcdoc Fallback für Edge/IE erklären

### ISSUE THREAD

**Issue by HoffmannP** [VeronaWorkgroup/VeronaInterface#6]
Da der IE und Edge in den bisher veröffentlichten Versionen im `iframe` kein `srcdoc`-Attribut unterstützen bitte ich entsprechend bewanderte Personen eine abstrakte Erläuterung des Angular-Fallbacks hinzuzufügen.
Die Notwendigkeit des Fallback wird jedoch hoffentlich in absehbarer Zeit verschwinden da der zukünftige Edge mit dem Aufbau auf Webkit das `srcdoc`-Attribute unterstützt.

**Comment by mechtelm** [comment]
Es handelt sich um einen JavaScript-Polyfill, hat nix mit Angular zu tun (übrigens MIT-Lizenz):
https://github.com/jugglinmike/srcdoc-polyfill

**Comment by HoffmannP** [comment]
Hat anscheinend nicht mal was mit Angular zu tun.
